version: "3.8"

services:
    # Cline Web Server
    cline-server:
        build:
            context: ./server
            dockerfile: Dockerfile
        ports:
            - "8000:8000"
        environment:
            - NODE_ENV=production
            - PORT=8000
            - DATABASE_PATH=/app/data/cline.db
            - CLIENT_URL=http://localhost:3000
            - JWT_SECRET=${JWT_SECRET:-your-jwt-secret-change-this}
            - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
            - OPENAI_API_KEY=${OPENAI_API_KEY}
        volumes:
            - ./data:/app/data
            - ./repositories:/app/repositories
            - /var/run/docker.sock:/var/run/docker.sock # For Docker-in-Docker if needed
        restart: unless-stopped
        healthcheck:
            test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
            interval: 30s
            timeout: 10s
            retries: 3
            start_period: 40s

    # Cline Web Client
    cline-client:
        build:
            context: ./client
            dockerfile: Dockerfile
            args:
                - VITE_API_URL=http://localhost:8000
                - VITE_WS_URL=ws://localhost:8000
        ports:
            - "3000:80"
        depends_on:
            - cline-server
        restart: unless-stopped

    # Nginx Reverse Proxy (Optional)
    nginx:
        image: nginx:alpine
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
            - ./nginx/ssl:/etc/nginx/ssl:ro
        depends_on:
            - cline-server
            - cline-client
        restart: unless-stopped
        profiles:
            - production

volumes:
    cline_data:
        driver: local
    cline_repositories:
        driver: local

networks:
    default:
        name: cline-network
